<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:context="http://www.springframework.org/schema/context"
	xmlns:aop="http://www.springframework.org/schema/aop" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:p="http://www.springframework.org/schema/p"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.1.xsd
	http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.1.xsd
	http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-3.1.xsd">
	<bean class="org.hope6537.springtest.aoptest.exception.PersonDaoImpl"
		id="personDao"></bean>
	<bean class="org.hope6537.springtest.aoptest.exception.PersonServiceImpl"
		id="personService">
		<property name="dao" ref="personDao"></property>
	</bean>
	<bean class="org.hope6537.springtest.aoptest.exception.PersonAction"
		id="personAction">
		<property name="service" ref="personService">
		</property>
	</bean>
	<bean class="org.hope6537.springtest.aoptest.exception.MyException"
		id="myException">
	</bean>

	<aop:config>
		<aop:pointcut
			expression="execution(* org.hope6537.springtest.aoptest.exception..*.*(..))"
			id="cud" />
		<aop:aspect ref="myException">

			<aop:after-throwing method="getExceptionMessage"
				throwing="ex" pointcut-ref="cud" />
		</aop:aspect>
	</aop:config>
</beans>